// Copyright 2026 John Suykerbuyk <john@syketech.com>
// SPDX-License-Identifier: Apache-2.0 OR MIT

package index

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/johns/vibe-vault/internal/mdutil"
)

// ContextOptions controls history.md rendering and pruning behavior.
type ContextOptions struct {
	AlertThreshold       int       // friction score threshold for alerts (0 = disabled)
	Now                  time.Time // reference time for recency (zero = time.Now())
	TimelineRecentDays   int       // full detail window (default 7)
	TimelineWindowDays   int       // condensed window (default 30)
	DecisionStaleDays    int       // decay threshold (default 90)
	KeyFilesRecencyBoost int       // multiplier for recent file sessions (default 3)
}

// normalize fills zero-value fields with sensible defaults.
func (o ContextOptions) normalize() ContextOptions {
	if o.Now.IsZero() {
		o.Now = time.Now()
	}
	if o.TimelineRecentDays <= 0 {
		o.TimelineRecentDays = 7
	}
	if o.TimelineWindowDays <= 0 {
		o.TimelineWindowDays = 30
	}
	if o.DecisionStaleDays <= 0 {
		o.DecisionStaleDays = 90
	}
	if o.KeyFilesRecencyBoost <= 0 {
		o.KeyFilesRecencyBoost = 3
	}
	return o
}

// Projects returns a sorted list of unique project names in the index.
func (idx *Index) Projects() []string {
	seen := make(map[string]bool)
	for _, e := range idx.Entries {
		seen[e.Project] = true
	}
	projects := make([]string, 0, len(seen))
	for p := range seen {
		projects = append(projects, p)
	}
	sort.Strings(projects)
	return projects
}

// ProjectContext generates an Obsidian markdown context document for a project.
func (idx *Index) ProjectContext(project string, opts ContextOptions) string {
	opts = opts.normalize()

	entries := idx.projectEntries(project)
	if len(entries) == 0 {
		return ""
	}

	// Sort chronologically
	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Date < entries[j].Date ||
			(entries[i].Date == entries[j].Date && entries[i].Iteration < entries[j].Iteration)
	})

	var b strings.Builder

	// Frontmatter
	b.WriteString("---\n")
	b.WriteString("type: project-context\n")
	fmt.Fprintf(&b, "project: %s\n", project)
	fmt.Fprintf(&b, "generated: %s\n", opts.Now.Format("2006-01-02T15:04:05"))
	fmt.Fprintf(&b, "sessions: %d\n", len(entries))
	b.WriteString("---\n\n")

	// Title
	fmt.Fprintf(&b, "# %s\n\n", project)

	// Session Timeline — tiered by recency
	recentCutoff := opts.Now.AddDate(0, 0, -opts.TimelineRecentDays)
	windowCutoff := opts.Now.AddDate(0, 0, -opts.TimelineWindowDays)

	b.WriteString("## Session Timeline\n\n")
	for _, e := range entries {
		entryDate := parseDate(e.Date)

		if entryDate.Before(windowCutoff) {
			// Older than window: omitted from timeline
			continue
		}

		noteName := filenameNoExt(e.NotePath)

		if !entryDate.Before(recentCutoff) {
			// Recent: full detail
			line := fmt.Sprintf("- [[%s]]", noteName)
			if e.ParentUUID != "" {
				line += " ↩continued"
			}
			if e.Tag != "" {
				line += fmt.Sprintf(" #%s", e.Tag)
			}
			if e.FrictionScore >= 30 {
				line += fmt.Sprintf(" ⚡%d", e.FrictionScore)
			}
			if e.Summary != "" {
				line += fmt.Sprintf(" — %s", e.Summary)
			}
			b.WriteString(line + "\n")
		} else {
			// Window: condensed (date, title/wikilink, tag only)
			line := fmt.Sprintf("- [[%s]]", noteName)
			if e.Tag != "" {
				line += fmt.Sprintf(" #%s", e.Tag)
			}
			b.WriteString(line + "\n")
		}
	}
	b.WriteString("\n")

	// Key Decisions — with staleness decay and permanence markers
	decisions := collectDecisionsWithDecay(entries, opts)
	if len(decisions) > 0 {
		b.WriteString("## Key Decisions\n\n")
		var lastDate string
		for _, d := range decisions {
			if d.date != lastDate {
				fmt.Fprintf(&b, "**%s**\n", d.date)
				lastDate = d.date
			}
			fmt.Fprintf(&b, "- %s\n", d.text)
		}
		b.WriteString("\n")
	}

	// Open Threads — from recent 5 sessions, excluding resolved
	threads := collectOpenThreads(entries)
	if len(threads) > 0 {
		b.WriteString("## Open Threads\n\n")
		for _, t := range threads {
			fmt.Fprintf(&b, "- [ ] %s\n", t)
		}
		b.WriteString("\n")
	}

	// Friction Alert — recent sessions above threshold
	if opts.AlertThreshold > 0 {
		frictionAlert := collectFrictionAlert(entries, opts.AlertThreshold)
		if frictionAlert != "" {
			b.WriteString(frictionAlert)
		}
	}

	// Friction Patterns — recurring high-friction signals
	frictionPatterns := collectFrictionPatterns(entries)
	if len(frictionPatterns) > 0 {
		b.WriteString("## Friction Patterns\n\n")
		for _, fp := range frictionPatterns {
			fmt.Fprintf(&b, "- %s\n", fp)
		}
		b.WriteString("\n")
	}

	// Key Files — with recency weighting
	keyFiles := collectKeyFilesWeighted(entries, opts)
	if len(keyFiles) > 0 {
		b.WriteString("## Key Files\n\n")
		for _, kf := range keyFiles {
			fmt.Fprintf(&b, "- `%s` (%d sessions)\n", kf.path, kf.count)
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n")
	b.WriteString("*Auto-generated by vv index*\n")

	return b.String()
}

func (idx *Index) projectEntries(project string) []SessionEntry {
	var entries []SessionEntry
	for _, e := range idx.Entries {
		if e.Project == project {
			entries = append(entries, e)
		}
	}
	return entries
}

type datedDecision struct {
	date string
	text string
}

// collectDecisionsWithDecay returns deduplicated decisions with staleness pruning.
// Decisions not referenced in recent sessions (within DecisionStaleDays) are dropped
// unless they contain [permanent] or [core] markers. Capped at 15 results.
func collectDecisionsWithDecay(entries []SessionEntry, opts ContextOptions) []datedDecision {
	staleCutoff := opts.Now.AddDate(0, 0, -opts.DecisionStaleDays)

	// First pass: collect unique decisions with their original date
	seen := make(map[string]bool)
	type decisionInfo struct {
		date     string
		text     string
		lastSeen string // date of most recent session referencing this decision
	}
	var allDecisions []decisionInfo

	for _, e := range entries {
		for _, d := range e.Decisions {
			if !seen[d] {
				seen[d] = true
				allDecisions = append(allDecisions, decisionInfo{
					date:     e.Date,
					text:     d,
					lastSeen: e.Date,
				})
			}
		}
	}

	// Second pass: update lastSeen by checking if later sessions reference
	// each decision (significant word overlap with summaries or decisions)
	for i := range allDecisions {
		dWords := mdutil.SignificantWords(allDecisions[i].text)
		if len(dWords) == 0 {
			continue
		}
		for _, e := range entries {
			if e.Date <= allDecisions[i].lastSeen {
				continue
			}
			// Check against session's decisions and summary
			if isReferencedIn(dWords, e) {
				allDecisions[i].lastSeen = e.Date
			}
		}
	}

	// Filter: keep decisions that are permanent, or whose lastSeen is recent enough
	var result []datedDecision
	for _, d := range allDecisions {
		if isPermanentDecision(d.text) {
			result = append(result, datedDecision{date: d.date, text: d.text})
			continue
		}
		lastSeenDate := parseDate(d.lastSeen)
		if !lastSeenDate.Before(staleCutoff) {
			result = append(result, datedDecision{date: d.date, text: d.text})
		}
	}

	// Cap at 15
	if len(result) > 15 {
		result = result[len(result)-15:]
	}

	return result
}

// isReferencedIn checks if a decision's significant words overlap with a session's
// decisions or summary.
func isReferencedIn(decisionWords []string, e SessionEntry) bool {
	// Check against each decision in the session
	for _, d := range e.Decisions {
		overlap := len(mdutil.SetIntersection(decisionWords, mdutil.SignificantWords(d)))
		if overlap >= 2 {
			return true
		}
	}
	// Check against summary
	if e.Summary != "" {
		overlap := len(mdutil.SetIntersection(decisionWords, mdutil.SignificantWords(e.Summary)))
		if overlap >= 2 {
			return true
		}
	}
	return false
}

// isPermanentDecision checks for [permanent] or [core] markers in decision text.
func isPermanentDecision(text string) bool {
	lower := strings.ToLower(text)
	return strings.Contains(lower, "[permanent]") || strings.Contains(lower, "[core]")
}

func collectOpenThreads(entries []SessionEntry) []string {
	// Collect all decisions for resolution checking
	var allDecisions []string
	for _, e := range entries {
		allDecisions = append(allDecisions, e.Decisions...)
	}

	// Take threads from last 5 sessions (entries already sorted chronologically)
	start := len(entries) - 5
	if start < 0 {
		start = 0
	}
	recent := entries[start:]

	seen := make(map[string]bool)
	var threads []string

	for _, e := range recent {
		for _, t := range e.OpenThreads {
			if seen[t] {
				continue
			}
			seen[t] = true

			// Check if resolved by any decision
			if isResolvedByDecisions(t, allDecisions) {
				continue
			}
			threads = append(threads, t)
		}
	}
	return threads
}

// isResolvedByDecisions checks if a thread has significant word overlap with any decision.
func isResolvedByDecisions(thread string, decisions []string) bool {
	threadWords := mdutil.SignificantWords(thread)
	if len(threadWords) == 0 {
		return false
	}
	for _, d := range decisions {
		decisionWords := mdutil.SignificantWords(d)
		overlap := len(mdutil.SetIntersection(threadWords, decisionWords))
		if overlap >= 2 {
			return true
		}
	}
	return false
}

type keyFile struct {
	path  string
	count int // weighted count for display, raw session count for sorting
}

// collectKeyFilesWeighted returns key files with recency-based weighting.
// Sessions within 14 days count boost×, within 30 days count 2×, older count 1×.
// Threshold: weighted score >= 5.
func collectKeyFilesWeighted(entries []SessionEntry, opts ContextOptions) []keyFile {
	recent14 := opts.Now.AddDate(0, 0, -14)
	recent30 := opts.Now.AddDate(0, 0, -30)
	boost := opts.KeyFilesRecencyBoost

	scores := make(map[string]int)
	rawCounts := make(map[string]int)

	for _, e := range entries {
		entryDate := parseDate(e.Date)
		var weight int
		switch {
		case !entryDate.Before(recent14):
			weight = boost
		case !entryDate.Before(recent30):
			weight = 2
		default:
			weight = 1
		}
		for _, f := range e.FilesChanged {
			scores[f] += weight
			rawCounts[f]++
		}
	}

	var files []keyFile
	for path, score := range scores {
		if score >= 5 {
			files = append(files, keyFile{path: path, count: rawCounts[path]})
		}
	}

	// Sort by weighted score descending, then path for stability
	sort.Slice(files, func(i, j int) bool {
		si, sj := scores[files[i].path], scores[files[j].path]
		if si != sj {
			return si > sj
		}
		return files[i].path < files[j].path
	})

	return files
}

func collectFrictionAlert(entries []SessionEntry, threshold int) string {
	// Use last 5 sessions
	start := len(entries) - 5
	if start < 0 {
		start = 0
	}
	recent := entries[start:]

	var sum, count, highCount int
	for _, e := range recent {
		if e.FrictionScore > 0 {
			sum += e.FrictionScore
			count++
			if e.FrictionScore >= threshold {
				highCount++
			}
		}
	}

	if count == 0 {
		return ""
	}

	avg := float64(sum) / float64(count)
	if avg < float64(threshold) {
		return ""
	}

	return fmt.Sprintf("## ⚠ Friction Alert\n\nRecent sessions average friction **%.0f** (threshold: %d).\n%d of %d recent sessions exceeded threshold.\nConsider: review recent corrections for recurring patterns.\n\n", avg, threshold, highCount, len(recent))
}

func collectFrictionPatterns(entries []SessionEntry) []string {
	var highFriction int
	var totalCorrections int
	var totalScore int
	scored := 0

	for _, e := range entries {
		if e.FrictionScore > 0 {
			scored++
			totalScore += e.FrictionScore
			totalCorrections += e.Corrections
			if e.FrictionScore >= 40 {
				highFriction++
			}
		}
	}

	if scored == 0 {
		return nil
	}

	var patterns []string

	if highFriction > 0 {
		patterns = append(patterns, fmt.Sprintf("%d of %d sessions had high friction (score ≥ 40)", highFriction, len(entries)))
	}

	if totalCorrections > 0 {
		patterns = append(patterns, fmt.Sprintf("%d total corrections across %d sessions", totalCorrections, scored))
	}

	avgScore := float64(totalScore) / float64(scored)
	if avgScore > 15 {
		patterns = append(patterns, fmt.Sprintf("Average friction score: %.0f/100", avgScore))
	}

	return patterns
}

func filenameNoExt(path string) string {
	base := filepath.Base(path)
	ext := filepath.Ext(base)
	if ext != "" {
		return base[:len(base)-len(ext)]
	}
	return base
}

// parseDate parses a YYYY-MM-DD date string, returning zero time on failure.
func parseDate(s string) time.Time {
	t, _ := time.Parse("2006-01-02", s)
	return t
}
