package index

import (
	"fmt"
	"sort"
	"strings"
	"time"
)

// CrossProjectKnowledge generates a cross-project knowledge document (_knowledge.md).
// Includes categories that span 2+ projects or contain project-agnostic notes.
func CrossProjectKnowledge(knowledge []KnowledgeSummary) string {
	if len(knowledge) == 0 {
		return ""
	}

	// Group by category
	type catEntry struct {
		projects map[string]bool
		notes    []KnowledgeSummary
	}
	categories := make(map[string]*catEntry)

	for _, k := range knowledge {
		cat := k.Category
		if cat == "" {
			cat = "general"
		}
		ce, ok := categories[cat]
		if !ok {
			ce = &catEntry{projects: make(map[string]bool)}
			categories[cat] = ce
		}
		ce.notes = append(ce.notes, k)
		if k.Project != "" {
			ce.projects[k.Project] = true
		}
	}

	// Filter: include category if it spans 2+ projects OR any note is agnostic
	var includedCats []string
	for cat, ce := range categories {
		hasAgnostic := false
		for _, n := range ce.notes {
			if n.Project == "" {
				hasAgnostic = true
				break
			}
		}
		if len(ce.projects) >= 2 || hasAgnostic {
			includedCats = append(includedCats, cat)
		}
	}

	if len(includedCats) == 0 {
		return ""
	}

	sort.Strings(includedCats)

	var b strings.Builder

	// Frontmatter
	b.WriteString("---\n")
	b.WriteString("type: cross-project-knowledge\n")
	b.WriteString(fmt.Sprintf("generated: %s\n", time.Now().Format("2006-01-02T15:04:05")))
	b.WriteString("---\n\n")
	b.WriteString("# Cross-Project Knowledge\n\n")

	for _, cat := range includedCats {
		ce := categories[cat]
		b.WriteString(fmt.Sprintf("## %s\n\n", cat))
		for _, n := range ce.notes {
			slug := filenameNoExt(n.NotePath)
			b.WriteString(fmt.Sprintf("- [[%s]] — %s\n", slug, n.Summary))
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n")
	b.WriteString("*Auto-generated by vv index*\n")

	return b.String()
}
