run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - unused
  disable:
    - gomnd
    - funlen
    - wsl
    - gochecknoglobals
    - gochecknoinits
    - exhaustruct
    - depguard
    - ireturn
    - varnamelen
    - nlreturn
    - wrapcheck
    - nonamedreturns
    - musttag
    - testpackage

linters-settings:
  govet:
    enable:
      - shadow
  errcheck:
    check-type-assertions: true
    check-blank: false
  staticcheck:
    checks:
      - all

issues:
  exclude-rules:
    # Allow unchecked errors in test files (e.g. cleanup calls)
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 5
