version: "2"
run:
  modules-download-mode: readonly
linters:
  disable:
    - depguard
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - ireturn
    - mnd
    - musttag
    - nlreturn
    - nonamedreturns
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    govet:
      enable:
        - shadow
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 5
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
