// Copyright 2026 John Suykerbuyk <john@syketech.com>
// SPDX-License-Identifier: Apache-2.0 OR MIT

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/suykerbuyk/vibe-vault/internal/agentregistry"
)

// internalUsage is the help text for the (operator-internal) `vv internal`
// command group. The plan calls these out as v2-portability scaffolding —
// they regenerate artifacts from the embedded agent catalogue. End users
// should not need to invoke these directly; `make install` runs them.
const internalUsage = `Usage: vv internal <subcommand> [flags]

Operator-internal commands. Not part of the user-facing surface.

Subcommands:
  generate-agents    Regenerate .claude/agents/<name>.md files from the
                     embedded agentregistry catalogue.

Flags for generate-agents:
  --out-dir <dir>    Output directory (default: .claude/agents).
`

// runInternal dispatches `vv internal <subcommand>`.
func runInternal() {
	args := os.Args[2:]
	if len(args) == 0 || wantsHelp(args) {
		fmt.Fprint(os.Stderr, internalUsage)
		if len(args) == 0 {
			os.Exit(1)
		}
		return
	}

	switch args[0] {
	case "generate-agents":
		runInternalGenerateAgents(args[1:])
	default:
		fmt.Fprintf(os.Stderr, "unknown internal command: %s\n", args[0])
		fmt.Fprint(os.Stderr, internalUsage)
		os.Exit(1)
	}
}

// runInternalGenerateAgents writes one markdown file per registered agent
// definition. Output is deterministic — running it twice produces byte-
// identical files — which is asserted by TestGenerator_Idempotent.
func runInternalGenerateAgents(args []string) {
	if wantsHelp(args) {
		fmt.Fprint(os.Stderr, internalUsage)
		return
	}
	outDir := flagValue(args, "--out-dir")
	if outDir == "" {
		outDir = filepath.Join(".claude", "agents")
	}

	count, err := generateAgentsTo(outDir, agentregistry.List())
	if err != nil {
		fatal("generate-agents: %v", err)
	}
	fmt.Printf("generate-agents: wrote %d file(s) to %s\n", count, outDir)
}

// generateAgentsTo writes one .md per definition into outDir. It returns the
// number of files written. The output is intentionally deterministic so
// `make install` produces no spurious diffs in source control.
func generateAgentsTo(outDir string, defs []*agentregistry.AgentDefinition) (int, error) {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return 0, fmt.Errorf("mkdir %s: %w", outDir, err)
	}
	written := 0
	for _, def := range defs {
		path := filepath.Join(outDir, def.Name+".md")
		content := renderAgentFile(def)
		// os.WriteFile truncates+rewrites — byte-identical content yields a
		// byte-identical file (modulo mtime), which is what idempotency
		// checks compare on.
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return written, fmt.Errorf("write %s: %w", path, err)
		}
		written++
	}
	return written, nil
}

// renderAgentFile produces the markdown text written to .claude/agents/<name>.md.
// Layout:
//
//	<auto-generated banner>
//	---
//	<frontmatter rendered in canonical key order>
//	---
//	<system prompt body>
//
// The frontmatter ordering is fixed (renderFrontmatterKeys) so output is
// byte-stable across runs.
func renderAgentFile(def *agentregistry.AgentDefinition) string {
	var sb strings.Builder
	sb.WriteString(autoGeneratedBanner(def.Name))
	sb.WriteString("---\n")
	sb.WriteString(renderFrontmatter(def))
	sb.WriteString("---\n")
	body := def.SystemPrompt
	body = strings.TrimRight(body, "\n")
	if body != "" {
		sb.WriteString(body)
		sb.WriteString("\n")
	}
	return sb.String()
}

// autoGeneratedBanner returns the HTML comment placed at the top of every
// generated file. It directs maintainers to the embedded source.
func autoGeneratedBanner(name string) string {
	return fmt.Sprintf("<!-- AUTO-GENERATED by 'vv internal generate-agents' from internal/agentregistry/agents/%s.md. DO NOT EDIT. v2-portability artifact. -->\n", name)
}

// renderFrontmatter serialises the AgentDefinition into the YAML-subset the
// embedded.go parser accepts. Keys are emitted in a fixed order.
func renderFrontmatter(def *agentregistry.AgentDefinition) string {
	var sb strings.Builder
	fmt.Fprintf(&sb, "name: %s\n", def.Name)
	fmt.Fprintf(&sb, "version: %q\n", def.Version)
	fmt.Fprintf(&sb, "description: %s\n", def.Description)
	fmt.Fprintf(&sb, "required_tools: %s\n", renderInlineList(def.RequiredTools))
	fmt.Fprintf(&sb, "forbidden_tools: %s\n", renderInlineList(def.ForbiddenTools))
	sb.WriteString("escalation_triggers:\n")
	// Block list — one item per line — sorted for byte stability.
	triggers := append([]string(nil), def.EscalationTriggers...)
	sort.Strings(triggers)
	for _, t := range triggers {
		fmt.Fprintf(&sb, "  - %s\n", t)
	}
	if def.OutputFormat != "" {
		sb.WriteString("output_format: |\n")
		for _, ln := range strings.Split(def.OutputFormat, "\n") {
			sb.WriteString("  ")
			sb.WriteString(ln)
			sb.WriteString("\n")
		}
	}
	fmt.Fprintf(&sb, "recommended_model_class: %s\n", def.RecommendedModelClass)
	return sb.String()
}

// renderInlineList emits a YAML inline list. Items are emitted verbatim;
// they may not contain commas, brackets, or newlines.
func renderInlineList(items []string) string {
	if len(items) == 0 {
		return "[]"
	}
	return "[" + strings.Join(items, ", ") + "]"
}
